const video_data=[
    {
        title:'丁真进军说唱圈,《zood》空降B榜',
        play:'2438.9万',
        video_src:'./videos/zood.mp4',
        likes:'96万',
        comments:'4.5万',
        coins:'94.5万',
        favorites:'65.3万',
        shares:'69.3万',
        watching:'114',
        UP_name:'理塘丁真',
        UP_avator:'./images/avatar/理塘丁真.png',
        UP_follower:'61.2万'
    },
    {
        title:'【SUFEx未来如风】当未来の风吹到了上财……',
        play:'743',
        video_src:'./videos/未来如风.mp4',
        likes:'743',
        comments:'17',
        coins:'64',
        favorites:'30',
        shares:'24',
        watching:'1',
        UP_name:'上财辣辣人同好会',
        UP_avator:'./images/avatar/上财辣辣人同好会.png',
        UP_follower:'34'
    },
    {
        title:'诗歌剧可爱集',
        play:'51.9万',
        video_src:'./videos/诗歌剧可爱集.mp4',
        likes:'1.6万',
        comments:'474',
        coins:'3573',
        favorites:'1.2万',
        shares:'6071',
        watching:'15',
        UP_name:'麦昆c',
        UP_avator:'./images/avatar/麦昆c.png',
        UP_follower:'9970'
    },
]